services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "443:443"
    environment:
      DOMAINS: "localhost -> http://web:8080, https-portal -> http://web:8080"
      STAGE: local
    depends_on:
      - web

  fluentd:
    build: ./apps/fluentd
    ports:
      - "9880:9880"
    environment:
      ENDPOINT_URL_PREFIX: "https://https-portal:443"
    depends_on:
      - https-portal

  web:
    build: ./apps/web
